version: '2'

services:
  master:
    build: .
    ports:
      - 9333:9333
    command: "master"
    networks:
      default:
        aliases:
          - seaweed_master
  volume:
    build: .
    ports:
      - 8080:8080
    command: 'volume -max=5 -mserver="master:9333" -port=8080'
    depends_on: 
     - master
    networks:
      default:
        aliases:
          - seaweed_volume
  filer:
    build: .
    ports: 
      - 8888:8888
    command: 'filer -master="master:9333"'
    depends_on:
      - master
      - volume 
    networks:
      default:
        aliases:
          - seaweed_filer
